import pandas as pd

from .averages import compute_averages_ave_sw_dw


def test_compute_averages_ave_sw_dw():
    """Write test for compute average pytest style
    TODO: update test, generated by co-pilot"""
    df = pd.DataFrame(
        {
            "symbol": ["A", "A", "A", "B", "B", "B"],
            "dollar": [1.0, 2.0, 2.0, 1.0, 1.0, 3.0],
            "size": [5.0, 2.0, 3.0, 1.0, 1.0, 3.0],
            "price": [1.0, 2.0, 3.0, 7.0, 2.0, 3.0],
        }
    )
    measures = ["price"]
    simple = True
    dollar_weighted = True
    share_weighted = True
    result = compute_averages_ave_sw_dw(
        df, measures, simple, dollar_weighted, share_weighted
    )
    expected = pd.DataFrame(
        {
            "price_Ave": [2.0, 4.0],
            "price_DW": [2.2, 3.6],
            "price_SW": [1.8, 3.6],
        },
        index=pd.Index(["A", "B"], name="symbol"),
    )
    pd.testing.assert_frame_equal(result, expected)
